#CUDA_VISIBLE_DEVICES=0 torchrun --nproc_per_node=1 --nnodes=1 --master_port=29500 FinetuningSurfClip.py -j 4 --save_path /data2/member/Xue/SurfClip/data/ADHD --surf_name ADHD_CT.npy --label_name ADHD_label.npy --finetune /data2/member/Xue/SurfClip/Output_single/No_ADHD_SurfCLIP_without_age_mask0.75/checkpoint_10.pt --output-dir ./Output_single/No_ADHD_CT_SurfCLIP_without_age_mask0.75_epoch10_5555 --data-seed 5555 --model finetuning_SurfClip_512_deeper_10_single_channel
#CUDA_VISIBLE_DEVICES=0 torchrun --nproc_per_node=1 --nnodes=1 --master_port=29500 FinetuningSurfClip.py -j 4 --save_path /data2/member/Xue/SurfClip/data/ADHD --surf_name ADHD_CT.npy --label_name ADHD_label.npy --finetune /data2/member/Xue/SurfClip/Output_single_woScalar/No_ADHD_SurfCLIP_without_age_mask0.75/checkpoint_10.pt --output-dir ./Output_single_woScalar/No_ADHD_CT_SurfCLIP_without_age_mask0.75_epoch10_5555 --data-seed 5555 --model finetuning_SurfClip_512_deeper_10_single_channel_woScalar
#CUDA_VISIBLE_DEVICES=0 torchrun --nproc_per_node=1 --nnodes=1 --master_port=29500 FinetuningSurfClip.py -j 4 --save_path /data2/member/Xue/SurfClip/data/ADHD --surf_name ADHD_CT.npy --label_name ADHD_label.npy --finetune /data2/member/Xue/SurfClip/Output_single/No_ADHD_SurfCLIP_ScalarConcat_mask0.75/checkpoint_10.pt --output-dir ./Output_single/No_ADHD_CT_SurfCLIP_ScalarConcat_mask0.75_epoch10_5555 --data-seed 5555 --model finetuning_SurfClip_512_deeper_10_single_channel_ScalarConcat
#CUDA_VISIBLE_DEVICES=0 torchrun --nproc_per_node=1 --nnodes=1 --master_port=29500 FinetuningSurfClip.py -j 4 --save_path /data2/member/Xue/SurfClip/data/ADHD --surf_name ADHD_CT.npy --label_name ADHD_label.npy --finetune /data2/member/Xue/SurfClip/Output_single/No_ADHD_SurfCLIP_woLCLIP_mask0.75/checkpoint_4.pt --output-dir ./Output_single/No_ADHD_CT_SurfCLIP_woLCLIP_mask0.75_epoch10_3333 --data-seed 3333 --model finetuning_SurfClip_512_deeper_10_single_channel

CUDA_VISIBLE_DEVICES=0 torchrun --nproc_per_node=1 --nnodes=1 --master_port=29500 FinetuningSurfClip.py -j 4 --save_path /data2/member/Xue/SurfClip/data/ASD --surf_name ASD_CT_r.npy --label_name ASD_label.npy --finetune /data2/member/Xue/SurfClip/Output_CLIP_single/No_ASD_CLIP/checkpoint_10.pt --output-dir ./Output_CLIP_single/No_ASD_CT_SurfCLIP_epoch10_1111 --data-seed 1111 --model Finetuning_CLIP_VITB16
#CUDA_VISIBLE_DEVICES=0 torchrun --nproc_per_node=1 --nnodes=1 --master_port=29500 FinetuningSurfClip.py -j 4 --save_path /data2/member/Xue/SurfClip/data/ASD --surf_name ASD_CT.npy --label_name ASD_label.npy --finetune /data2/member/Xue/SurfClip/Output_single/No_ASD_SurfCLIP_woTeacher_mask0.75/checkpoint_10.pt --output-dir ./Output_single/No_ASD_CT_SurfCLIP_mask0.75_epoch10_1111 --data-seed 1111 --model finetuning_SurfClip_512_deeper_10_single_channel
CUDA_VISIBLE_DEVICES=0 torchrun --nproc_per_node=1 --nnodes=1 --master_port=29500 FinetuningSurfClip.py -j 4 --save_path /data2/member/Xue/SurfClip/data/ASD --surf_name ASD_CT_r.npy --label_name ASD_label.npy --finetune /data2/member/Xue/SurfClip/Output_DetailCLIP_single/No_ASD_CLIP/checkpoint_10.pt --output-dir ./Output_DetailCLIP_single/No_ASD_CT_SurfCLIP_epoch10_1111 --data-seed 1111 --model finetune_DetailCLIP
CUDA_VISIBLE_DEVICES=0 torchrun --nproc_per_node=1 --nnodes=1 --master_port=29500 FinetuningSurfClip.py -j 4 --save_path /data2/member/Xue/SurfClip/data/ASD --surf_name ASD_CT_r.npy --label_name ASD_label.npy --finetune /data2/member/Xue/SurfClip/Output_ACLIP_single/No_ASD_ACLIP/checkpoint_10.pt --output-dir ./Output_ACLIP_single/No_ASD_CT_SurfCLIP_epoch10_1111 --data-seed 1111 --model Finetuning_ACLIP_VITB16
CUDA_VISIBLE_DEVICES=0 torchrun --nproc_per_node=1 --nnodes=1 --master_port=29500 FinetuningCAR.py -j 4 --save_path /data2/member/Xue/SurfClip/data/ASD --surf_name ASD_CT_r.npy --label_name ASD_label.npy --finetune /data2/member/Xue/SurfClip/Output_CAR_single/No_ASD_CARCLIP/checkpoint_10.pt --output-dir ./Output_CAR_single/No_ASD_CT_SurfCLIP_epoch10_1111 --data-seed 1111 --model finetune_CAR

#CUDA_VISIBLE_DEVICES=0 torchrun --nproc_per_node=1 --nnodes=1 --master_port=29500 FinetuningSurfClip.py -j 4 --save_path /data2/member/Xue/SurfClip/data/ASD --surf_name ASD_CT.npy --label_name ASD_label.npy --finetune /data2/member/Xue/SurfClip/Output_single/No_ASD_SurfCLIP_woTeacher_mask0.75/checkpoint_10.pt --output-dir ./Output_single/No_ASD_CT_SurfCLIP_mask0.75_epoch10_1111 --data-seed 1111 --model finetuning_SurfClip_512_deeper_10_single_channel
#CUDA_VISIBLE_DEVICES=0 torchrun --nproc_per_node=1 --nnodes=1 --master_port=29500 FinetuningSurfClip.py -j 4 --save_path /data2/member/Xue/SurfClip/data/ADHD --surf_name ADHD_CT.npy --label_name ADHD_label.npy --finetune /data2/member/Xue/SurfClip/Output_single/No_ADHD_SurfCLIP_without_sex_mask0.75/checkpoint_10.pt --output-dir ./Output_single/No_ADHD_CT_SurfCLIP_without_sex_mask0.75_epoch10_5555 --data-seed 5555 --model finetuning_SurfClip_512_deeper_10_single_channel
#CUDA_VISIBLE_DEVICES=0 torchrun --nproc_per_node=1 --nnodes=1 --master_port=29500 FinetuningSurfClip.py -j 4 --save_path /data2/member/Xue/SurfClip/data/ADHD --surf_name ADHD_CT.npy --label_name ADHD_label.npy --finetune /data2/member/Xue/SurfClip/Output_single/No_ADHD_SurfCLIP_mask0.6/checkpoint_10.pt --output-dir ./Output_single/No_ADHD_CT_SurfCLIP_mask0.6_epoch10_5555 --data-seed 5555 --model finetuning_SurfClip_512_deeper_10_single_channel
#CUDA_VISIBLE_DEVICES=0 torchrun --nproc_per_node=1 --nnodes=1 --master_port=29500 FinetuningSurfClip.py -j 4 --save_path /data2/member/Xue/SurfClip/data/ADHD --surf_name ADHD_CT.npy --label_name ADHD_label.npy --finetune /data2/member/Xue/SurfClip/Output_single/No_ADHD_SurfCLIP_mask0.8/checkpoint_10.pt --output-dir ./Output_single/No_ADHD_CT_SurfCLIP_mask0.8_epoch10_5555 --data-seed 5555 --model finetuning_SurfClip_512_deeper_10_single_channel
#CUDA_VISIBLE_DEVICES=0 torchrun --nproc_per_node=1 --nnodes=1 --master_port=29500 FinetuningSurfClip.py -j 4 --save_path /data2/member/Xue/SurfClip/data/ADHD --surf_name ADHD_CT.npy --label_name ADHD_label.npy --finetune /data2/member/Xue/SurfClip/Output_single/No_ADHD_SurfCLIP_mask0.9/checkpoint_10.pt --output-dir ./Output_single/No_ADHD_CT_SurfCLIP_mask0.9_epoch10_5555 --data-seed 5555 --model finetuning_SurfClip_512_deeper_10_single_channel


#CUDA_VISIBLE_DEVICES=0 torchrun --nproc_per_node=1 --nnodes=1 --master_port=29500 FinetuningSurfClip.py -j 4 --save_path /data2/member/Xue/SurfClip/data/CHD --surf_name CHD_CT.npy --label_name CHD_label.npy --finetune /data2/member/Xue/SurfClip/Output_single/No_CHD_SurfCLIP/checkpoint_10.pt --output-dir ./Output_single/No_CHD_CT_SurfCLIPtemp_epoch10_7777 --data-seed 7777 --model finetuning_SurfClip_512_deeper_10_single_channel

#CUDA_VISIBLE_DEVICES=0 torchrun --nproc_per_node=1 --nnodes=1 --master_port=29500 FinetuningCAR.py -j 4 --save_path /data2/member/Xue/SurfClip/data/ADHD --surf_name ADHD_CT.npy --label_name ADHD_label.npy --finetune /data2/member/Xue/SurfClip/Output_CAR_single/No_ADHD_CARCLIP/checkpoint_10.pt --output-dir ./Output_CAR_single/No_ADHD_CT_SurfCLIP_epoch10_1111 --data-seed 1111 --model finetune_CAR
#CUDA_VISIBLE_DEVICES=0 torchrun --nproc_per_node=1 --nnodes=1 --master_port=29500 FinetuningCAR.py -j 4 --save_path /data2/member/Xue/SurfClip/data/CHD --surf_name CHD_CT.npy --label_name CHD_label.npy --finetune /data2/member/Xue/SurfClip/Output_CAR_single/No_CHD_CARCLIP/checkpoint_10.pt --output-dir ./Output_CAR_single/No_CHD_CT_SurfCLIP_epoch10_1111 --data-seed 1111 --model finetune_CAR
#CUDA_VISIBLE_DEVICES=0 torchrun --nproc_per_node=1 --nnodes=1 --master_port=29500 FinetuningCAR.py -j 4 --save_path /data2/member/Xue/SurfClip/data/AD --surf_name AD_CT.npy --label_name AD_label.npy --finetune /data2/member/Xue/SurfClip/Output_CAR_single/No_ADNI_CARCLIP/checkpoint_10.pt --output-dir ./Output_CAR_single/No_ADNI_CT_SurfCLIP_epoch10_1111 --data-seed 1111 --model finetune_CAR



#CUDA_VISIBLE_DEVICES=3 torchrun --nproc_per_node=1 --nnodes=1 --master_port=29503 FinetuningParcellationSurfClip.py -j 4 --save_path /data2/member/Xue/SurfClip/data/HCP --surf_name HCP_CT.npy --label_name HCP_vertex_label.npy --finetune /data2/member/Xue/SurfClip/Output_single/No_HCP_SurfCLIP/checkpoint_10.pt --output-dir ./Output_single/No_HCP_parcellation_CT_SurfCLIP_epoch10_1111 --data-seed 1111 --model Parcellation_finetuning_SurfClip_512_deeper_10_single_channel

#CUDA_VISIBLE_DEVICES=0 torchrun --nproc_per_node=1 --nnodes=1 --master_port=29501 FinetuningRegressionSurfClip.py -j 4 --surf_name HCP_CT.npy --output-dir ./Output_ACLIP_single/No_HCP_ACLIP_epoch10_age_CT_simple --data-seed 2222 --model Finetuning_Regression_ACLIP_VITB16 --finetune /data2/member/Xue/SurfClip/Output_ACLIP_single/No_HCP_ACLIP/checkpoint_10.pt

#CUDA_VISIBLE_DEVICES=0 torchrun --nproc_per_node=1 --nnodes=1 --master_port=29501 FinetuningRegressionSurfClip.py -j 4 --surf_name HCP_MC.npy --output-dir ./Output_CLIP_single/No_HCP_ACLIP_epoch10_age_CT_simple --data-seed 2222 --model Finetuning_Regression_CLIP_VITB16 --finetune /data2/member/Xue/SurfClip/Output_CLIP_single/No_HCP_ACLIP/checkpoint_10.pt

#CUDA_VISIBLE_DEVICES=0 torchrun --nproc_per_node=1 --nnodes=1 --master_port=29501 FinetuningRegressionSurfClip.py -j 4 --surf_name HCP_MC.npy --output-dir ./Output_DetailCLIP_single/No_HCP_ACLIP_epoch10_age_CT_simple --data-seed 2222 --model finetune_regression_DetailCLIP --finetune /data2/member/Xue/SurfClip/Output_DetailCLIP_single/No_HCP_ACLIP/checkpoint_10.pt
#CUDA_VISIBLE_DEVICES=0 torchrun --nproc_per_node=1 --nnodes=1 --master_port=29501 FinetuningRegressionSurfClipCAR.py -j 4 --surf_name HCP_CT.npy --output-dir ./Output_CAR_single/No_HCP_CARCLIP_epoch10_age_CT_simple --data-seed 2222 --model finetune_regression_CAR --finetune /data2/member/Xue/SurfClip/Output_CAR_single/No_HCP_CARCLIP/checkpoint_10.pt

#CUDA_VISIBLE_DEVICES=3 torchrun --nproc_per_node=1 --nnodes=1 --master_port=29505 FinetuningRegressionSurfClip.py -j 4 --surf_name HCP_CT.npy --output-dir ./Output_single/No_HCP_SurfCLIP_epoch10_age_CT_simpler --data-seed 2222 --model regression_finetuning_SurfClip_512_deeper_10_single_channel --finetune /data2/member/Xue/SurfClip/Output_single/No_HCP_SurfCLIP/checkpoint_10.pt
