#PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True torchrun --nproc_per_node=4 --nnodes=1 TrainAClip.py  -j 4 --root_path ./data_surfclip --train_image_filename No_ASD_single_1.npy --train_text_filename No_ASD_text_ACLIP_single.npy --output-dir /data2/member/Xue/SurfClip/Output_ACLIP_single/No_ASD_ACLIP/

#PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True torchrun --nproc_per_node=4 --nnodes=1 TrainCARZERO.py  -j 4 --root_path ./data_surfclip --train_image_filename No_ASD_single_1.npy --train_text_filename No_ASD_text_ACLIP_single.npy --output-dir /data2/member/Xue/SurfClip/Output_CAR_single/No_ASD_CARCLIP

#PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True torchrun --nproc_per_node=4 --nnodes=1 TrainOriClip.py  -j 4 --root_path ./data_surfclip --train_image_filename No_ASD_single_1.npy --train_text_filename No_ASD_text_ACLIP_single.npy --output-dir /data2/member/Xue/SurfClip/Output_CLIP_single/No_ASD_CLIP/

#PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True torchrun --nproc_per_node=4 --nnodes=1 TrainDetailClip.py  -j 4 --root_path ./data_surfclip --train_image_filename No_ASD_single_1.npy --train_text_filename No_ASD_text_ACLIP_single.npy --output-dir /data2/member/Xue/SurfClip/Output_DetailCLIP_single/No_ASD_CLIP

#./CT.sh

#./MC.sh

#./SD.sh

#PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True torchrun --nproc_per_node=4 --nnodes=1 TrainSurfClip.py  -j 4 --root_path ./data_surfclip --train_image_filename No_ASD_single.npy --train_text_filename No_ASD_text_embeddings_single.npy --output-dir /data2/member/Xue/SurfClip/Output_single/No_ASD_SurfCLIP_1_mask0.75 --mask-ratio 0.75 --weight_mask 0.7 --model SurfClip_512_deeper_10_single_channel

#PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True torchrun --nproc_per_node=4 --nnodes=1 TrainCARZERO.py  -j 4 --root_path ./data_surfclip --train_image_filename No_ASD_single.npy --train_text_filename No_ASD_text_ACLIP_single.npy --output-dir /data2/member/Xue/SurfClip/Output_CAR_single/No_ASD_CARCLIP

#PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True torchrun --nproc_per_node=4 --nnodes=1 TrainSurfClipWoTokenizer.py  -j 4 --root_path ./data_surfclip --train_image_filename No_ADHD_single.npy --train_text_filename No_ADHD_text_embeddings_single.npy --output-dir /data2/member/Xue/SurfClip/Output_single_woToken/No_ADHD_SurfCLIP --mask-ratio 0.75 --weight_mask 0.7 --model SurfClip_512_deeper_10_single_channel_woToken
#PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True torchrun --nproc_per_node=4 --nnodes=1 TrainSurfClipWoTokenizer.py  -j 4 --root_path ./data_surfclip --train_image_filename No_CHD_single.npy --train_text_filename No_CHD_text_embeddings_single.npy --output-dir /data2/member/Xue/SurfClip/Output_single_woToken/No_CHD_SurfCLIP --mask-ratio 0.75 --weight_mask 0.7 --model SurfClip_512_deeper_10_single_channel_woToken
#PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True torchrun --nproc_per_node=4 --nnodes=1 TrainSurfClipWoTokenizer.py  -j 4 --root_path ./data_surfclip --train_image_filename No_ADNI_single.npy --train_text_filename No_ADNI_text_embeddings_single.npy --output-dir /data2/member/Xue/SurfClip/Output_single_woToken/No_ADNI_SurfCLIP --mask-ratio 0.75 --weight_mask 0.7 --model SurfClip_512_deeper_10_single_channel_woToken

#PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True torchrun --nproc_per_node=4 --nnodes=1 TrainSurfClipWoOther.py  -j 4 --root_path ./data_surfclip --train_image_filename No_ADHD_single.npy --train_text_filename No_ADHD_text_embeddings_single.npy --output-dir /data2/member/Xue/SurfClip/Output_single_woSpherical/No_ADHD_SurfCLIP --mask-ratio 0.75 --weight_mask 0.7 --model SurfClip_512_deeper_10_single_channel_woSpherical
#PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True torchrun --nproc_per_node=4 --nnodes=1 TrainSurfClipWoOther.py  -j 4 --root_path ./data_surfclip --train_image_filename No_CHD_single.npy --train_text_filename No_CHD_text_embeddings_single.npy --output-dir /data2/member/Xue/SurfClip/Output_single_woSpherical/No_CHD_SurfCLIP --mask-ratio 0.75 --weight_mask 0.7 --model SurfClip_512_deeper_10_single_channel_woSpherical
#PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True torchrun --nproc_per_node=4 --nnodes=1 TrainSurfClipWoOther.py  -j 4 --root_path ./data_surfclip --train_image_filename No_ADNI_single.npy --train_text_filename No_ADNI_text_embeddings_single.npy --output-dir /data2/member/Xue/SurfClip/Output_single_woSpherical/No_ADNI_SurfCLIP --mask-ratio 0.75 --weight_mask 0.7 --model SurfClip_512_deeper_10_single_channel_woSpherical

#PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True torchrun --nproc_per_node=4 --nnodes=1 TrainSurfClipWoOther.py  -j 4 --root_path ./data_surfclip --train_image_filename No_ADHD_single.npy --train_text_filename No_ADHD_text_embeddings_single.npy --output-dir /data2/member/Xue/SurfClip/Output_single_woTransformer/No_ADHD_SurfCLIP --mask-ratio 0.75 --weight_mask 0.7 --model SurfClip_512_deeper_10_single_channel_woTransformer
#PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True torchrun --nproc_per_node=4 --nnodes=1 TrainSurfClipWoOther.py  -j 4 --root_path ./data_surfclip --train_image_filename No_CHD_single.npy --train_text_filename No_CHD_text_embeddings_single.npy --output-dir /data2/member/Xue/SurfClip/Output_single_woTransformer/No_CHD_SurfCLIP --mask-ratio 0.75 --weight_mask 0.7 --model SurfClip_512_deeper_10_single_channel_woTransformer
#PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True torchrun --nproc_per_node=4 --nnodes=1 TrainSurfClipWoOther.py  -j 4 --root_path ./data_surfclip --train_image_filename No_ADNI_single.npy --train_text_filename No_ADNI_text_embeddings_single.npy --output-dir /data2/member/Xue/SurfClip/Output_single_woTransformer/No_ADNI_SurfCLIP --mask-ratio 0.75 --weight_mask 0.7 --model SurfClip_512_deeper_10_single_channel_woTransformer

#PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True torchrun --nproc_per_node=4 --nnodes=1 TrainSurfClipWoOther.py  -j 4 --root_path ./data_surfclip --train_image_filename No_ADHD_single.npy --train_text_filename No_ADHD_text_embeddings_single.npy --output-dir /data2/member/Xue/SurfClip/Output_single_woScalar/No_ADHD_SurfCLIP --mask-ratio 0.75 --weight_mask 0.7 --model SurfClip_512_deeper_10_single_channel_woScalar
#PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True torchrun --nproc_per_node=4 --nnodes=1 TrainSurfClipWoOther.py  -j 4 --root_path ./data_surfclip --train_image_filename No_CHD_single.npy --train_text_filename No_CHD_text_embeddings_single.npy --output-dir /data2/member/Xue/SurfClip/Output_single_woScalar/No_CHD_SurfCLIP --mask-ratio 0.75 --weight_mask 0.7 --model SurfClip_512_deeper_10_single_channel_woScalar
#PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True torchrun --nproc_per_node=4 --nnodes=1 TrainSurfClipWoOther.py  -j 4 --root_path ./data_surfclip --train_image_filename No_ADNI_single.npy --train_text_filename No_ADNI_text_embeddings_single.npy --output-dir /data2/member/Xue/SurfClip/Output_single_woScalar/No_ADNI_SurfCLIP --mask-ratio 0.75 --weight_mask 0.7 --model SurfClip_512_deeper_10_single_channel_woScalar

#PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True torchrun --nproc_per_node=4 --nnodes=1 TrainSurfClipWoOther.py  -j 4 --root_path ./data_surfclip --train_image_filename No_HCP_single.npy --train_text_filename No_HCP_text_embeddings_single.npy --output-dir /data2/member/Xue/SurfClip/Output_single_woScalar/No_HCP_SurfCLIP --mask-ratio 0.75 --weight_mask 0.7 --model SurfClip_512_deeper_10_single_channel_woScalar
#PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True torchrun --nproc_per_node=4 --nnodes=1 TrainSurfClipWoOther.py  -j 4 --root_path ./data_surfclip --train_image_filename No_HCP_single.npy --train_text_filename No_HCP_text_embeddings_single.npy --output-dir /data2/member/Xue/SurfClip/Output_single_woTransformer/No_HCP_SurfCLIP --mask-ratio 0.75 --weight_mask 0.7 --model SurfClip_512_deeper_10_single_channel_woTransformer
#PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True torchrun --nproc_per_node=4 --nnodes=1 TrainSurfClipWoOther.py  -j 4 --root_path ./data_surfclip --train_image_filename No_HCP_single.npy --train_text_filename No_HCP_text_embeddings_single.npy --output-dir /data2/member/Xue/SurfClip/Output_single_woSpherical/No_HCP_SurfCLIP --mask-ratio 0.75 --weight_mask 0.7 --model SurfClip_512_deeper_10_single_channel_woSpherical

#PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True torchrun --nproc_per_node=4 --nnodes=1 TrainSurfClipWoTeacher.py  -j 4 --root_path ./data_surfclip --train_image_filename No_ADHD_single.npy --train_text_filename No_ADHD_text_embeddings_single.npy --output-dir /data2/member/Xue/SurfClip/Output_single/No_ADHD_SurfCLIP_woTeacher_mask0.75 --mask-ratio 0.75 --weight_mask 0.7 --model SurfClip_512_deeper_10_single_channel_woTeacherStudent

#PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True torchrun --nproc_per_node=4 --nnodes=1 TrainSurfClipWoTeacher.py  -j 4 --root_path ./data_surfclip --train_image_filename No_ADHD_single.npy --train_text_filename No_ADHD_text_embeddings_single.npy --output-dir /data2/member/Xue/SurfClip/Output_single/No_ADHD_SurfCLIP_woTeacher_mask0.75 --mask-ratio 0.8 --weight_mask 0.7 --model SurfClip_512_deeper_10_single_channel_woTeacherStudent

#PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True torchrun --nproc_per_node=4 --nnodes=1 TrainSurfClipWoTeacher.py  -j 4 --root_path ./data_surfclip --train_image_filename No_ADHD_single.npy --train_text_filename No_ADHD_text_embeddings_single.npy --output-dir /data2/member/Xue/SurfClip/Output_single/No_ADHD_SurfCLIP_woTeacher_mask0.75 --mask-ratio 0.85 --weight_mask 0.7 --model SurfClip_512_deeper_10_single_channel_woTeacherStudent

#PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True torchrun --nproc_per_node=4 --nnodes=1 TrainSurfClipWoTeacher.py  -j 4 --root_path ./data_surfclip --train_image_filename No_ADHD_single.npy --train_text_filename No_ADHD_text_embeddings_single.npy --output-dir /data2/member/Xue/SurfClip/Output_single/No_ADHD_SurfCLIP_woTeacher_mask0.75 --mask-ratio 0.9 --weight_mask 0.7 --model SurfClip_512_deeper_10_single_channel_woTeacherStudent

#PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True torchrun --nproc_per_node=4 --nnodes=1 TrainSurfClip.py  -j 4 --root_path ./data_surfclip --train_image_filename No_ASD_single.npy --train_text_filename No_ASD_text_embeddings_single.npy --output-dir /data2/member/Xue/SurfClip/Output_single/No_ASD_SurfCLIP_mask0.75 --mask-ratio 0.75 --weight_mask 0.7 --model SurfClip_512_deeper_10_single_channel

PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True torchrun --nproc_per_node=4 --nnodes=1 TrainSurfClip.py  -j 4 --root_path ./data_surfclip --train_image_filename No_ADHD_single.npy --train_text_filename No_ADHD_text_embeddings_single.npy --output-dir /data2/member/Xue/SurfClip/Output_single/No_ADHD_SurfCLIP_ScalarConcat_BatchNorm_mask0.75 --mask-ratio 0.75 --weight_mask 0.7 --model SurfClip_512_deeper_10_single_channel_ScalarConcat_BatchNorm

#PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True torchrun --nproc_per_node=4 --nnodes=1 TrainSurfClip.py  -j 4 --root_path ./data_surfclip --train_image_filename 0_12_single.npy --train_text_filename 0_12_text_embeddings_single.npy --output-dir /data2/member/Xue/SurfClip/Output_single/0_12_SurfCLIP_mask0.75 --mask-ratio 0.75 --weight_mask 0.7 --model SurfClip_512_deeper_10_single_channel

#PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True torchrun --nproc_per_node=4 --nnodes=1 TrainSurfClip.py  -j 4 --root_path ./data_surfclip --train_image_filename 12_18_single.npy --train_text_filename 12_18_text_embeddings_single.npy --output-dir /data2/member/Xue/SurfClip/Output_single/12_18_SurfCLIP_mask0.75 --mask-ratio 0.75 --weight_mask 0.7 --model SurfClip_512_deeper_10_single_channel

#PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True torchrun --nproc_per_node=4 --nnodes=1 TrainSurfClip.py  -j 4 --root_path ./data_surfclip --train_image_filename 18_55_single.npy --train_text_filename 18_55_text_embeddings_single.npy --output-dir /data2/member/Xue/SurfClip/Output_single/18_55_SurfCLIP_mask0.75 --mask-ratio 0.75 --weight_mask 0.7 --model SurfClip_512_deeper_10_single_channel

#PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True torchrun --nproc_per_node=4 --nnodes=1 TrainSurfClip.py  -j 4 --root_path ./data_surfclip --train_image_filename 55_95_single.npy --train_text_filename 55_95_text_embeddings_single.npy --output-dir /data2/member/Xue/SurfClip/Output_single/55_95_SurfCLIP_mask0.75 --mask-ratio 0.75 --weight_mask 0.7 --model SurfClip_512_deeper_10_single_channel



